### ISSUE TITLE
File Fingerprints

### ISSUE THREAD

**Issue by Kneelawk** [amcoder/Curse.RestProxy#3]
I am looking for a way to verify file downloads on completion. I have found the "fingerprint" and "package_fingerprint" nodes when requesting add on file information but I have no idea what format these fingerprints are in. The fingerprints do not seem to match CRC32, Adler32 or anything else I've tried and I am not sure if there is a standard format for concatenating or summing with versions or ids.

Thank you for the proxy, it really makes things easier.

**Comment by amcoder** [comment]
You're welcome!

I couldn't figure out how the fingerprints work either, unfortunately. My guess is that it is something custom and without seeing their source it's going to be hard to figure out. I gave up on it. 😞 

If you ever figure it out, let me know and I will add it to the wiki.
